on:
  push:
    branches:
      - '**'

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --frozen-lockfile
      - run: yarn test --collectCoverage=true
      - run: yarn format
      - run: git diff --exit-code
      - run: yarn build
      - uses: codecov/codecov-action@v3
